# Generated by Django 4.1.7 on 2023-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
